- name: Home
  pages:
    - page: pages/welcome_page.py
      title: Home
      icon: ":material/home:"
      default: true
      header: Home
      caption: Welcome to the Home page of the Streamlit app
      help_page: null
    - page: pages/search_financial_statement.py
      title: Search Financial Statements
      icon: ":material/data_table:"
      default: true 
      header: ?
      caption: Search for SEC reported financial statements by company and month. 
      help_page: null

